### ISSUE TITLE
Theme issue: range can only initialize variable

### ISSUE THREAD

**Issue by Porkepix** [Exodus-Privacy/website#30] opened 2019-09-10 11:18 UTC
Currently build fail on recent version, at least 0.57 and earlier, maybe older than that.

See the error message:

```
Error: add site dependencies: load resources: loading templates: "website/themes/hugo-bootstrap/layouts/section/code.html:6:1": parse failed: template: section/code.html:6: range can only initialize variables
```

**Comment by Porkepix** [comment] 2019-09-10 11:25
After some tests, it broke with 0.55.

**Comment by simpnu** [comment] 2019-09-16 05:55
We need to discuss what we want to do here.

The current theme is working with versions >= 0.40,  <= 0.54.
If we want to use the latest versions of hugo, we need to update the theme and test it thoroughly, then update hugo on our production machines.

Otherwise we could specify the hugo versions in our README.

**Comment by MeTaLPoU** [comment] 2020-10-25 14:09
I was looking for a new theme to support the latest versions of Hugo. At first, i tried with some Bootstrap themes like https://themes.gohugo.io/tags/bootstrap/ 
But after a few tests, i think it's better to look into the multilingual themes : https://themes.gohugo.io/tags/multilingual/

Two of them seems fine : 
-> https://themes.gohugo.io/hugo-eureka/ 
-> https://themes.gohugo.io/gohugo-theme-ananke/

I 
![eureka](https://user-images.githubusercontent.com/37960027/97109477-b83f5180-16d3-11eb-934c-cf7a107d40fc.png)
![ananke](https://user-images.githubusercontent.com/37960027/97109479-b8d7e800-16d3-11eb-94b9-4d06683f2ef3.png)

I don't know if it's a good idea to choose the theme before working on https://github.com/Exodus-Privacy/website/issues/111 because it seems to need a lot of work to adapt the existing website to the new theme.

**Comment by kerouanton** [comment] 2021-06-13 09:50
Issue still present, at least on latest hugo version (0.83.1).
Steps to reproduce:
```sh
git clone https://github.com/Exodus-Privacy/website
cd website
hugo server -D
```

**Comment by Jean-BaptisteC** [comment] 2024-03-20 21:22
I close the issue, we have planned to migrate to pelican.

**Closed by Jean-BaptisteC** 2024-03-20 21:22 UTC
Labels: question
